#!/usr/bin/env lua

dofile "/usr/okpkg/okpkg.lua"

os.execute [[ rm -fr /usr/okpkg/sources && mkdir /usr/okpkg/sources ]]

pkgs = {
    "iana-etc", "glibc", "zlib", "bzip2", "xz", "zstd", "file", "m4", "bc", 
    "flex", "pkgconf", "binutils", "gmp", "mpfr", "libmpc", "attr", "acl", 
    "libxcrypt", "isl", "gcc13", "binutils", "which", "gperf", "libcap", 
    "libmd", "libbsd", "shadow", "ncurses", "readline", "sed", "psmisc", 
    "bison", "pcre2", "grep", "bash", "expat", "inetutils", "less", "tcsh", 
    "mawk", "tzdata", "perl", "libressl", "kmod", "curl", "python3", "samurai", 
    "meson", "coreutils", "check", "diffutils", "findutils", "pigz", "libtirpc",
    "iproute2", "kbd", "make", "lzip", "ed", "patch", "tar", "lua", "vim", 
    "eudev", "mandoc", "procps-ng", "util-linux", "dcron", "e2fsprogs", 
    "libarchive", "sysklogd", "dbus", "openresolv", "dhcpcd", "dinit", 
    "libxml2", "libxslt", "iputils",  "acpid", "cmake", "dma", "at", 
    "dosfstools", "htop", "git", "gnupg1", "libpcap", "iftop", "popt", 
    "logrotate", "lsof", "lzo", "lzop", "nano", "openbsd-netcat", "openntpd", 
    "openssh", "pax", "rsync", "s-nail", "sharutils", "sudo", "time",
    "libevent", "tmux",
    "gzip", "gawk"
}
for i=1,#pkgs do download(pkgs[i]); end

