#!/usr/bin/env lua

dofile "/usr/okpkg/scripts/init"
dofile "/usr/okpkg/okpkg.lua"

-- 7. Entering Chroot and Building Additional Temporary Tools 
tmp = {
    "bison", "perl", "libxcrypt", "zlib", "pigz", "bzip2", "expat", "python3", 
    "util-linux"
}
for i=1,#tmp do emerge(tmp[i]); end

-- 8. Installing Basic System Software 
pkgs = {
    "iana-etc", "glibc", "zlib", "bzip2", "xz", "zstd", "file", "m4", "bc", 
    "flex", "pkgconf", "binutils", "gmp", "mpfr", "libmpc", "attr", "acl", 
    "libxcrypt", "gcc13", "binutils", "which", "gperf", "libcap", "libmd", 
    "libbsd", "shadow", "ncurses", "readline", "sed", "psmisc", "bison", 
    "pcre2", "grep", "bash", "expat", "inetutils", "less", "perl", "libressl", 
    "kmod", "curl", "python3", "samurai", "meson", "coreutils", "check", 
    "diffutils", "mawk", "tzdata", "findutils", "pigz", "iproute2", "kbd", 
    "make", "lzip", "ed", "patch", "tar", "lua", "vim", "eudev", "mandoc", 
    "procps-ng", "util-linux", "e2fsprogs", "libarchive", "sysklogd", "dbus", 
    "openresolv", "dhcpcd", "dinit", "libxml2", "libxslt", "iputils", "dcron", 
    "dosfstools", "htop", "gnupg1", "nano", "sharutils", "sudo", "time", 
    "libevent", "tmux",
}
for i=1,#pkgs do emerge(pkgs[i]); end

-- Split GCC
os.execute("/usr/okpkg/scripts/split-gcc.sh")

-- If you want to rebuild everything, comment out below:
os.exit()

-- These are kept separate to the base system, to avoid circular dependencies,
-- and keep the system minimal:
pkgs = {
    "tcsh", "pax", "dma", "at", "s-nail", "openssh", "zsh",
    "acpid2", "git", "lzo", "lzop", "rsync",
    "popt", "logrotate", "libaio", "lvm2", "parted", "popt", "efivar", 
    "efibootmgr", "grub2", 
    "libmnl", "libnftnl", 
    "cmake", "db1", "nvi", "json-c", "argon2", "cryptsetup", 
    "libusb", "usbutils", "pciutils", 
    "libtirpc", "lsof",
    "libpcap", "iftop",
    "openblas", "r",
    "libyaml", "ruby",
    "elfutils",
}
for i=1,#pkgs do emerge(pkgs[i]); end
