#!/usr/bin/env lua

package.cpath = package.cpath .. ";/usr/okpkg/?.so"

require "okutils"

local unpack = unpack or table.unpack

setenv("DESTDIR", "/mnt")
chdir("/usr/okpkg/packages/base")

function install(pkgname)
    local cmd = [[ bsdtar -P -C "$DESTDIR" -xf "%s"-*.tar.xz ]]
    os.execute(string.format(cmd, pkgname))
end

minimal = {
    "acl", "attr", "bash", "bzip2", "coreutils", "curl", "dbus", "dhcpcd", 
    "dinit", "dcron", "e2fsprogs", "ed", "eudev", "expat", "file", "findutils",
    "gcc-libs", "glibc", "gmp", "grep", "iana-etc", "inetutils", "iproute2", 
    "iputils", "kbd", "kmod", "less", "libarchive", "libbsd", "libcap", 
    "libmd", "libressl", "libxcrypt", "lua", "mawk", "ncurses", "openresolv", 
    "patch", "pcre2", "pigz", "procps-ng", "readline", "sed", "shadow", 
    "sysklogd", "tar", "time", "tzdata", "util-linux", "which", "xz", "zlib", 
    "zstd", "db1", "nvi", "sharutils",
}

base = {
    "linux-headers", "iana-etc", "glibc", "zlib", "bzip2", "xz", "zstd", 
    "file", "m4", "bc", "flex", "pkgconf", "binutils", "gmp", "mpfr", "libmpc", 
    "attr", "acl", "libxcrypt", "gcc-libs", "gcc-13.2.0", "binutils", "which", 
    "gperf", "libcap", "libmd", "libbsd", "shadow", "ncurses", "readline", 
    "sed", "psmisc", "bison", "pcre2", "grep", "bash", "expat", "inetutils", 
    "less", "tcsh", "perl", "libressl", "kmod", "curl", "python3", "samurai", 
    "meson", "coreutils", "check", "diffutils", "mawk", "tzdata", "findutils", 
    "pigz", "iproute2", "kbd", "make", "lzip", "ed", "patch", "tar", "lua", 
    "vim", "eudev", "mandoc", "procps-ng", "util-linux", "dcron", "e2fsprogs", 
    "libarchive", "sysklogd", "dbus", "openresolv", "dhcpcd", "dinit", 
    "libxml2", "libxslt", "iputils",  "acpid2", "cmake", "db1", "dma", "at", 
    "dosfstools", "htop", "gnupg1", "popt", "logrotate", "lzo", "lzop", 
    "nano", "openssh", "pax", "rsync", "s-nail", "sharutils", "sudo", "time", 
    "libevent", "tmux",
}

devel = {
    "git", "zsh", "json-c", "argon2", 
    "libaio", "lvm2", "parted"
    "efivar", "efibootmgr", "grub2", 
}

posix = {
    "bc", "dma", "s-nail", "lprng", "pax", "diffutils", unpack(minimal)
}

while #arg > 0 do
    for i=1,#_G[arg[1]] do
        install(_G[arg[1]][i])
    end
    table.remove(arg, 1)
end
