#!/bin/sh

SOURCE_DATE_EPOCH=1000000000

cd $1

# strip debugging, delete unneeded files, etc.
{
    strip -S usr/lib64/*
    strip -s usr/bin/* bin/*
    rm -r usr/share/doc usr/doc usr/share/info
    find . -name '*.pyc' -delete
} 2>/dev/null

tar --sort=name \
    --mtime=@$SOURCE_DATE_EPOCH \
    --owner=0 \
    --group=0 \
    --numeric-owner \
    --create \
    --file=$1.tar *

cd ..

xz -T0 -f $1.tar && rm -r $1
