#!/bin/bash

export DESTDIR=/mnt

umount -l "$DESTDIR"
read -p "Enter partition to format: " PART 
mkfs.ext4 "$PART"
mount "$PART" "$DESTDIR"

lua /usr/okpkg/scripts/filesystem.lua "$DESTDIR"
cp /etc/ssl/certs/ca-certificates.crt "$DESTDIR"/etc/ssl/certs
git clone /usr/okpkg "$DESTDIR"/usr/okpkg    
git -C "$DESTDIR"/usr/okpkg repack -adf --depth=1
cp -p /usr/okpkg/download/* /mnt/usr/okpkg/download
