#!/bin/bash

export DESTDIR=/mnt

umount -l "$DESTDIR"
read -p "Enter partition to format: " PART 
mkfs.ext4 "$PART"
mount "$PART" "$DESTDIR"

lua /usr/okpkg/scripts/filesystem.lua "$DESTDIR"
cp /etc/ssl/certs/ca-certificates.crt "$DESTDIR"/etc/ssl/certs
git -C /usr/okpkg archive --prefix=okpkg/ master | 
    bsdtar -C "$DESTDIR"/usr -xf -
cp -rp /usr/okpkg/download/* /mnt/usr/okpkg/download
